[package]
name = "codefuse"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
anyhow = "1.0.100"
futures = "0.3.31"

[dependencies.tower-lsp]
version = "0.20.0"
default-features = true
features = ["runtime-tokio"]
