[package]
name = "codefuse"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.86"
duct = "1.1.0"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }

[dependencies.tower-lsp]
version = "0.20.0"
default-features = true
features = ["runtime-tokio"]